-- ============================================================
-- DEPRECATED — do not run this file.
--
-- This project previously carried two conflicting schemas: this one and
-- database.sql. Neither matched what the application actually queries, which
-- caused several features to fail at runtime.
--
-- The single source of truth is now:
--
--     ../database.sql
--
-- Run that file in the Supabase SQL Editor instead. It is idempotent and
-- non-destructive, and it migrates databases created from either old schema.
-- ============================================================
